default: &default
  adapter: postgresql
  encoding: unicode
  user:
  host: localhost
  pool: 25

development:
  <<: *default
  database: test_app_development

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
